### ISSUE TITLE
Produce build for version 0.5.0

### ISSUE THREAD

**Issue by mivade** [conda-forge/typing_inspect-feedstock#2]
Version 0.5.0 of `typing_inspect` was released on 2019-10-13. Could we please get an updated build?

**Comment by mivade** [comment]
This is what #1 is about.

**Comment by tarcisioe** [comment]
Closed by #1. Sorry for the delay. In the end the issue that prevented the merge was the lack of a new dependency that was already in conda-forge. Should work now :)

**Comment by mivade** [comment]
Thanks!
